version: '3.8'

services:

  app_node:
    container_name: app_node
    build: 
      context: ./app/
    networks:
      - nginx-node
    volumes: 
      - ./app:/home/app
    tty: true
    depends_on: 
      - mysqldb
    restart: always
    
  mysqldb:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysqldb
    restart: always
    tty: true
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump/:/docker-entrypoint-initdb.d/
    environment: 
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-node

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    tty: true
    ports:
      - "8080:80"
    restart: always
    links:
      - app_node
    depends_on: 
      - app_node
    networks:
      - nginx-node

networks:
  nginx-node:
    driver: bridge
      